[tasks.run-all-examples]
script_runner = "python"
script_extension = "py"
script = '''
import sys
import os
import subprocess
import time

print("The following command will run examples one by one.")
print("Those that start with `faililing_` should fail.")
input("Press Enter to continue...")

for example in os.listdir('examples'):
    if not(example.endswith('.rs')):
        continue

    example = example[:-3]
    
    print()
    print('Running example: ' + example)

    env = os.environ.copy()
    env['RUST_BACKTRACE'] = '0'
    
    subprocess.run(['cargo', 'run', '-q', '--example', example], env=env)
    
    if example.startswith('failing_'):
        print()
        input("Press Enter to continue...")
'''